### ISSUE TITLE
Scraper is pulling in applications with no date_received

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/greater_geelong#4] opened 2020-01-31 05:05 UTC
As discussed on https://github.com/openaustralia/planningalerts/issues/1379, the scraper is pulling in applications without including a date_received (see https://www.planningalerts.org.au/applications/1531070 for an example) which leads to people getting alerts for very old applications (see linked front conversations)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_27h6t)

**Comment by muzza1976** [comment] 2020-01-31 06:45
The problem is latest delivery to update the scraper has used table#ctl00_ContentBody_GV_FINISHED instead of table#ctl00_ContentBody_GV_CURRENT
The open pull request will sort this.

**Comment by jamezpolley** [comment] 2020-01-31 06:58
Thanks for that @muzza1976!

That doesn't actually fix this problem though... it fixes a different problem that I hadn't noticed yet. I've raised #5 for that issue :)

**Comment by jamezpolley** [comment] 2020-01-31 07:06
@mlandauer I'm not sure what to do here. If I've read your comments on https://github.com/openaustralia/planningalerts/issues/1379 right, the scraper should *never* pull in an application without a date_received, as without that PlanningAlerts will not be able to tell which applications are new.

However, I can't see how to get a date_received out of the website - the closest I can see is the `Advertised Start` date, but we're already using that as `on_notice_from` (or will be once #3  is accepted).

So I don't know what to do here. Do you have any suggestions?

**Comment by mlandauer** [comment] 2020-02-05 00:37
@jamezpolley that's not correct. It's perfectly valid (though far from ideal) for an application not to have a `date_received`.

The documentation at https://www.planningalerts.org.au/how_to_write_a_scraper says that `date_received` is an optional field. 

If you look at the code for how PlanningAlerts decides that an application is "new" and needs to be emailed to someone: https://github.com/openaustralia/planningalerts/blob/d54f735e50a5f80a30d483dc07147e0d9ebaed9c/app/services/process_alert_service.rb#L11 and  https://github.com/openaustralia/planningalerts/blob/d54f735e50a5f80a30d483dc07147e0d9ebaed9c/app/models/alert.rb#L35. You can see that what it does is look for applications that been created for the first time (so ignoring updates) and that have their `date_scraped` set to later than the last time the person received an email alert. So, in other words, it does *not* take the `date_received` in to account when deciding what to email people exactly because we can not depend on it being there (because it's optional).

**Comment by mlandauer** [comment] 2020-02-05 00:38
So, this is not a bug. Closing.

**Closed by mlandauer** 2020-02-05 00:38 UTC
